nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: Test
            description:
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        path_patterns:
            - ^/api